hrsh7th/nvim-compe

lua/compe_nvim_lsp/source.lua
possible fix of #2 . After adding those lines and few test, I no longer have the aforementioned error message. Not sure if its the right solution to the issue.
=> fix(nvim_lsp): attempt to index local result L60

README.md, autoload/compe_tags/source.vim
This is just a simple source that wraps built in tags completion.
=> Add tags source.

autoload/compe_tags/source.vim
Fixes issue mentioned in [this comment](https://github.com/hrsh7th/nvim-compe/issues/30#issuecomment-733608801)
=> Fix tags completion to always use fresh input.

README.md, after/plugin/compe_ultisnips.vim, lua/compe_ultisnips/init.lua
Hello @hrsh7th , as discussed in #65 , This PR adds ultisnips completion source. If something is missing from the standard, I would modify it accordingly. :sweat_smile:
=> Added Ultisnips builtin completion source

README.md, autoload/compe/helper.vim, autoload/compe/source/vim_bridge.vim, autoload/compe_lamp/source.vim, autoload/compe_path/source.vim, autoload/compe_tags/source.vim, autoload/compe_vim_lsp/source.vim, autoload/compe_vsnip/source.vim, lua/compe/completion.lua, lua/compe/helper.lua, lua/compe/matcher.lua, lua/compe/source.lua, lua/compe/vim_bridge.lua, lua/compe_buffer/init.lua, lua/compe_nvim_lsp/source.lua, lua/compe_nvim_lua/init.lua, lua/compe_ultisnips/init.lua
@hrsh7th Assuming that the `datermine` function is meant to determine whether or not completion should occur for the source, here's a spelling typo correction PR. If this is not the case, let me know.
=> datermine -> determine

README.md, after/plugin/compe_spell.vim, autoload/compe_spell/source.vim
https://github.com/hrsh7th/nvim-compe/issues/85
@coxackie What do you think about it?
=> spell source

autoload/compe_path/source.vim, autoload/compe_tags/source.vim, autoload/compe_vsnip/source.vim, lua/compe_buffer/init.lua
Follow up to https://github.com/hrsh7th/nvim-compe/pull/91#issuecomment-769665330
Did I miss anything?
=> Use capitalised source labels

README.md, autoload/compe.vim, lua/compe/source.lua
=> Use feedkeys

README.md, doc/compe.txt, lua/compe_snippets_nvim/init.lua
I was originally just want to fix the broken link for `matcher.lua` but ended up adding more stuff to the readme, edited the wiki and added documentation preview for `snippets.nvim` source :laughing:
=> docs: more details

README.md, after/plugin/compe_calc.vim, doc/compe.txt, lua/compe_calc/init.lua
Add my favorite source.
I don't satisfy suggestions. if someone has an idea, feel free to create PR.
=> Add calc source

README.md, doc/compe.txt
@hrsh7th @elianiva I restructured the vim docs, what do you think about it?
=> New vim docs structure

lua/compe/config.lua
=> Fixed setting enabled to false

README.md
=> docs: added demo

after/plugin/compe_vim_lsc.vim, autoload/compe/helper.vim, autoload/compe_vim_lsc/source.vim, lua/compe/helper.lua, lua/compe_nvim_lsp/source.lua
If it is not enough, please create PR (because I don't use vim-lsc now).
Related https://github.com/hrsh7th/nvim-compe/issues/120#issuecomment-772225612
=> Add LSC source

README.md, doc/compe.txt, lua/compe/completion.lua, lua/compe/config.lua, lua/compe/source.lua, lua/compe/utils/string.lua
=> Add max_abbr_width/max_kind_width/max_menu_width

README.md, after/plugin/compe_treesitter.vim, doc/compe.txt, lua/compe_treesitter/init.lua
I don't use it personally but if people coming from completion.nvim want to have this source on nvim-compe as well, might worth to merge this in. Otherwise, feel free to close this PR if no one wants it.
=> feat: added treesitter source

README.md
Closes #141 
This is what I am using, perhaps it can be improved somehow?
=> Update README.md with example tab mapping

README.md, doc/compe.txt, lua/compe/completion.lua, lua/compe/config.lua
=> Add new option to change documentation behaviour

autoload/compe/documentation.vim, autoload/compe_vim_lsc/source.vim, autoload/compe_vim_lsp/source.vim, autoload/vital/_compe/VS/LSP/CompletionItem.vim, lua/compe/completion.lua, lua/compe/config.lua, lua/compe/context.lua, lua/compe/helper.lua, lua/compe/init.lua, lua/compe/source.lua, lua/compe/utils/character.lua, lua/compe/vim_bridge.lua, lua/compe_nvim_lsp/source.lua
Fixes #156
Fixes #153
This PR is buggy now. But it would improve some of the cases.
=> Fix column

lua/compe/completion.lua, lua/compe/config.lua, lua/compe/context.lua, lua/compe/helper.lua, lua/compe/init.lua, lua/compe/source.lua, lua/compe/utils/async.lua
=> Improve context handling

README.md
=> Mention snippets.nvim LSP support in README

after/plugin/compe_snippets_nvim.vim, after/plugin/compe_treesitter.vim
pcall takes a function as its first argument.
This broke my snippets :upside_down_face:
=> Fix pcall calls

lua/compe_snippets_nvim/init.lua
Fixed wrong use of `vim.bo.filetype` in `lua/compe_snippets_nvim/init.lua`.
=> multiple filetypes for Snippets.nvim Fix #283

README.md, after/plugin/compe_luasnip.vim, lua/compe_luasnip/init.lua
Hi, I've written a nvim-compe source for LuaSnip-snippets, is it alright if it's in nvim-compe or should I put it somewhere in LuaSnip?
=> Add source for LuaSnip.

README.md
Updated README file with a link to https://github.com/andersevenrud/compe-tmux
=> Add tmux external source to documentation

lua/compe_ultisnips/init.lua
Closes #327. Adds logic to show UltiSnips preview when selecting a snippet.
=> Add UltiSnips documentation preview

README.md, autoload/compe/confirmation.vim
Thanks to https://github.com/SirVer/ultisnips/issues/964 and https://github.com/hrsh7th/nvim-compe/pull/236 I was able to add UltiSnips support for LSP snippets.
Linked issue: https://github.com/hrsh7th/nvim-compe/issues/362.
=> Add UltiSnips support for LSP snippets

autoload/compe/confirmation.vim, lua/compe/matcher.lua, lua/compe/utils/string.lua, lua/compe_buffer/buffer.lua
=> Choose word more smarter

README.md
=> docs: fixed docs for new documentation float

lua/compe_luasnip/init.lua
=> fix: change LuaSnip's menu field to LuaSnip

README.md
Adding another external source to the repo readme.
=> Add lbdb as additional external source

lua/compe_omni/init.lua
@hrsh7th please check this PR. Thanks.
=> Fix typo in keyword pattern
