hrsh7th/nvim-compe

lua/compe/completion.lua
Hello @hrsh7th, Opening a PR so we can discuss in terms of code. #61 shows
weird backspace behavior.
I feel `vim.fn.complete` should be called when the GUI event is taking place in
nvim-event-loop. This PR currently adds `vim.schedule` wrapper around it. At least
this solves it in my machine. What is the effect on your environment?
If not solves in your environment I can change work over code more as I am
interested in this cool project. :smile:
=> call vim.fn.complete when event loop is processing GUI event

lua/compe/completion.lua
Hi @hrsh7th, in ``Completion._show`` function, vimscript ``complete`` function
is called every time even if there are no elements in ``items``.
When items are empty, we get a ``Pattern not found`` error message. This is classic
with vim's completion mechanism. However, this can be so distracting for users
many times.
This pull request adds a condition around the complete function to be called only
when there are some elements in the ``items`` table.
This removes the ``Pattern not found`` error message significantly while typing.
=> call vimscript complete only when there are items in completion list

autoload/compe_tags/source.vim
This PR adds documentation floating window for tags completion that contains all file paths where tag is defined.
This is useful when you rely a lot on tags completion (which I do in javascript projects), and i'm not always 100% sure if certain thing exist in certain file. This helps a lot.
Here are few screenshots:
Less than 10 entries:
10 entries is maximum. Everything else is truncated:
=> Add documentation for tags completion that contains all file paths.

autoload/compe_tags/source.vim
I noticed that there are a lot of duplicate paths for tags documentation that I added today, even on the screenshot I attached:
This is how it looks now:
There are still some duplicates since the list is not sorted, but I don't want to sort it since things should be sorted as they appear in tags file, at least that seems more natural to me. So much duplicates are generally very rare and only for keywords that occur so much.
=> Remove duplicate paths from tags completion documentation.

lua/compe/completion.lua
Hello @hrsh7th, This PR indents to refresh current completion even if no new
items are there for source. (i.e., when #source.items == 0)
This may not be the best way to achieve it, but it certainly would improve
behavior.
I would show it in gif.
Before:
After:
If you feel there is a better way to achieve it please tell me, I would change that in PR.:smiley:
=> refresh completion when no new items are available

after/plugin/compe_ultisnips.vim, lua/compe_ultisnips/init.lua
Use `vim.F.npcall` to catch error instead, allowing ultisnips to be added to `&rtp` after nvim startup. Useful for those who do on-demand loading using built-in packages.
Also, the `match()` was reliant on the `ignorecase` setting; in my case (`noignorecase` set), it failed to match ultisnips even though it is installed and added via `packadd! ultisnips` in init.vim.
With this change, `vim.F.npcall()` will return `nil` if the call to `UltiSnips#{...}` fails -- meaning someone has added ultisnips as a completion source but doesn't have it loaded in nvim.
=> Remove &rtp search for ultisnips

README.md
I met some people that get confused by nvim-compe docs so I tried to "improve" the docs so people can get started more easily. Some things might be missing like `allow_prefix_unmatch` because I don't know what this option does and maybe some other explanations.
I was thinking of adding how to use this with other autopairs such as `nvim-autopairs` because you have an example for `lexima` but I'm not sure if that's the scope of this project.
edit: I can also help converting the readme into vimdocs if you want :)
=> docs: improved docs

README.md, lua/compe/completion.lua, lua/compe/config.lua
if `let g:compe.autocomplete` is set to false, completion only triggers manually
fix #88
Let me know if you want to change the name to something better.
`completion-nvim` calls it `completion_enable_auto_popup`.
=> Add option to disable autocomplete

lua/compe_ultisnips/init.lua
Add a confirm function for the ultisnips completion source. Ultisnips normally has its own expand trigger, but mapping it to `<CR>` can be problematic as it interferes with a lot of other plugins that try to map the same key. When used in conjunction with such plugins, I think it is better to defer to nvim-compe's completion.
=> Add Ultisnips Confirm Function

lua/compe/context.lua, lua/compe_buffer/init.lua, lua/compe_nvim_lsp/init.lua, lua/compe_path/init.lua, lua/compe_vsnip/init.lua
use `vim.api` to replace `vim.fn` when possible, the performance should increase slightly, I think.
I did this because I saw this chat on Neovim's Gitter.
I haven't tested it thoroughly cause I don't have enough time atm, but from what I experienced, nothing's broken.
=> refactor: move vim.fn to vim.api whenever possible

autoload/compe/documentation.vim
Sometimes Neovim fails to delete swapfiles which can result in repeated error messages upon re-opening the editor
Thanks for maintaining this really nice plugin!
=> fix: avoid creating swapfiles for preview buffers

README.md, doc/compe.txt
- fixed invalid formatting in vim docs
- fixed links to FAQ in table of contents in README.md
I saw some people asking how to expand snippets from the completion menu. There was no mention how to do that.
=> Add snippet expansion to docs and FAQ

README.md, after/plugin/compe_omni.vim, doc/compe.txt, lua/compe_omni/init.lua
This is a basic source that works, but I think that it should be filetype-specific, because it is only relevant in a few cases (e.g. when editing LaTeX files when https://github.com/lervag/vimtex is installed). However, there isn't a good way for users to configure filetypes for sources right now, since they don't have access to the source metadata.
It would be easy to add a global option and read it in `get_metadata` but that's quite ugly in my opinion.
Ideally, I'd like to configure filetypes via files in an `ftplugin` directory (which only works for Vimscript, [Lua support is planned for 0.6](https://github.com/neovim/neovim/issues/12670), which is still far away) or autocommands. I feel that it shouldn't be the responsibility of a plugin to handle filetype management since (Neo)Vim …
=> Add omni completion source

lua/compe_nvim_lsp/source.lua
Some servers will respond with the detail field, but with an empty
string. If this happens an empty window is shown. This just adds another
simple check to ensure that the window isn't shown if the detail is ''.
Before:
After:
=> Don't show resolve is detail is ''.

autoload/compe/documentation.vim, lua/compe/completion.lua, lua/compe/source.lua, lua/compe/utils/async.lua
1. Avoid too many compe#documentation calls
- done
2. Avoid too many table.sort calls
- I had wrong thoughts. We can't it.
I have a very large TypeScript codebase. nvim-compe will have a lag if completion in it.
Finally, I found a solution that just removes the `in_fast_event` check in the async.lua.
=> Improve perf

autoload/compe.vim
=> Add `compe#confirm({ 'select': v:true, 'keys': '<CR>' })`

lua/compe/completion.lua
This fixes an issue i had trying to use nvim-compe while editing files with foldmarkers and a modeline. Everytime i pressed enter to confirm a completion item all my folds were getting closed. I found out that `doautocmd` reloads the `modeline` which caused `foldlevel=0` from my modeline to be run again. Fortunately this can be suppressed using the `<nomodeline>` flag. I replaced every `doautocmd` call with `doautocmd <nomodeline>`.
Use the following file and command to reproduce: `nvim --clean -u test.vim test.vim`
```vim
" Test {{{
set modeline
au User Test echom 'test'
" }}}
" vim: foldmethod=marker foldenable foldlevel=0
```
=> Fix problem with doautocmd and modeline

README.md
Hi!
I made a simple source to insert unicode symbols by autocompleting latex \codes. I'd like to add it to README external sources list.
=> Add compe-latex-symbols to external sources list

autoload/compe/confirmation.vim
Hi, I recently wrote a [snippet plugin](https://github.com/L3MON4D3/LuaSnip) for Neovim and would like to add some support for it here.
=> Optionally expand LSP-Snippets with LuaSnip

lua/compe_luasnip/init.lua
Luasnip only deletes the trigger while compe inserts the snippet-name, should no longer be an issue with this.
=> Bugfix for Luasnip-source

lua/compe_luasnip/init.lua
Using `name` as word breaks completion displaying a lot of options.
This proposal use name and dscr to improve documentation and keep trigger as text.
=> Improve LuaSnip completion

lua/compe_path/init.lua
Adds support for path autocompletion using environment variables such as `$HOME` and `$PWD`. Can be used in the following manner: `$PWD/tests/`.
Fixes #320, fixes #322.
=> Support Environment Variables in Path Completion

lua/compe/matcher.lua
I'm receiving `Error executing vim.schedule lua callback: .../site/pack/packer/start/nvim-compe/lua/compe/matcher.lua:26: attempt to get length of local 'word' (a nil value)`, when editing lua files.
This should fix the issue.
=> Fix #410: attempt to get length of local 'word' (a nil value)

lua/compe/config.lua
I've noticed that [the docs](https://github.com/hrsh7th/nvim-compe/blob/master/doc/compe.txt#L257-L260) and the [README](https://github.com/hrsh7th/nvim-compe/blob/master/README.md) say that throttle time defaults to 80 but [the code](https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/config.lua#L4) says otherwise. This is a fix for that.
=> fix default throttle time

README.md
For this function, using an `if` statement to `return` a boolean value is the same as just returning that value directly. The one caveat is that `:match` doesn't return a bool value, so we have to convert it into a boolean value by testing for `~= nil`.
=> ref(README): simplify `check_back_space`

README.md
Previously, there was a `vim.fn.call` invocation which was used to call vsnip autoload functions (assumedly, because they use the special `#` syntax). However, this can be done with `vim.fn['vsnip#foo']` directly.
=> ref(README): call `vsnip#` functions directly

lua/compe_nvim_lsp/source.lua
This PR fixes #440
I also pushed a fix upstream to fix this https://github.com/neovim/neovim/pull/14989
But this PR will also fix it for people using 0.5
=> fix(documentation): make a copy of the completion result to prevent double escaping of plaintext

README.md
This PR highlights the latest stable release of neovim (v0.5.0)
=> Removed comment on nightly in `README`

lua/compe_spell/init.lua
This makes spell completion respect `set nospell`.
The current conditional `vim.wo.spell == 0` will always return false.
=> Make spell completion respect vim spell option

lua/compe_nvim_lsp/source.lua
Fixup for my previous PR.
This adds a check if the doc is a table. Only then do we make a deep copy. Would fail otherwise for some lsp servers
=> fix(documentation): check if doc is table before deep copy

lua/compe_tags/init.lua
Actually, I would like to put `tag.kind` in the `menu` entry near the `[T]` symbol (e.g. `f [T]` as a symbol for a function would be nice. I don't know how to achieve that, though...
Other things that could be added is the context from the file around the specific line, if the line is available; it could substitute the exe cmd used to find the tag
=> Added more documentation info for tags

lua/compe_luasnip/init.lua
LSP-snippets may have tables as description, which causes an error here.
=> Account for multiline descriptions in luasnip-source.

lua/compe_nvim_lsp/source.lua
I actually fixed this in the past already here:
https://github.com/hrsh7th/nvim-compe/commit/4df0108195dfbc36f6143a7d0e1f6bf6418432b8,
but it looks like is snuck back in. Some servers will still return a
`detail` field in the completion item with an empty string. Currently
this is causing an extra empty window to appear. This small change just
makes sure the detail isn't empty, and if it is, don't show the window.
Before:
After:
=> Fix regression with showing empty resolve window

lua/compe/float.lua
It turns out that the height of the doc window is the number of lines
in the text. The problem here is that each code blocks contain two extra
lines which will be removed by `stylize_markdown` function and thus the
extra space.
The problem does not seem to appear in any of the LSP floating window
because of the order the functions are being invoked. `stylize_markdown`
needs to be invoked first which will remove those code fences and apply
the syntax highlighting and then we should be calculating the height of
the floating window.
Fixes: #456 
cc @folke Could you take a look at this as this is your forte :)
_Before:_
_After:_
=> fix: don't render blank lines at the bottom

lua/compe_nvim_lsp/source.lua
Don't show empty docs.
This actually led to an error in the float module since we tried rendering a float of width `0`
=> fix: don't show empty doc for lsp

lua/compe/source.lua, lua/compe_ultisnips/init.lua
Fixed by passing the metadata as one of the arguments to the 'source.complete' function. Then, check if 'kind' is set in the metadata. The default is still 'Snippet'.
=> Fixes #400

.github/stale.yml
I dislike bots like this generally, but I especially think it's
disheartening to auto-reject PRs. I'd think more than twice
about contributing to a project if I thought my contribution
would eventually be closed by a bot. For an example, see
https://github.com/hrsh7th/nvim-compe/pull/378#issuecomment-898434903
=> stale: Disable on pull requests

README.md
All links are displayed in one line. I think it would be better for readability if each link would be displayed on a separate line.
=> Fix formatting in known-issues section

lua/compe_luasnip/init.lua
In this change https://github.com/L3MON4D3/LuaSnip/commit/a1580b62beaffad0d631219d1b14764b17ab63aa
LuaSnip removed global table `Luasnip_current_nodes`
which now needs to be accessed as `luasnip.session.current_nodes`
=> Fix broken Luasnip integration
